### ISSUE TITLE
Error with rsat_download()

### ISSUE THREAD

**Issue by jfmas** [ropensci/rsat#18]
Hi,

I followed the vignette number 2 "Download" and get the following error when running rsat_download(filomena)

> rsat_download(filomena)
Ordering on ESPA platform...
Error in (new("refMethodDef", .Data = function (espa_orders, db_path,  : 
  argument "espa_orders" is missing, with no default

This occurs using both credentials from the vignette and mines.

Regards,

JF

**Comment by viniciovcl** [comment]
Hi,

Just wanted to share that I've encountered the same error mentioned in this thread. 

Thanks in advance for any help!

**Comment by unai-perez** [comment]
Fixed in github version
