### ISSUE TITLE
Landsat and Sentinel data unavoilable

### ISSUE THREAD

**Issue by Fredtouz** [ropensci/rsat#2]
Hi all,
it seems that only MODIS data are curently available, here is an example that works:
roi <- ex.navarre
toi <- as.Date("2020-01-11")
rtp <- tempdir()
dbp <- file.path(tempdir(), "DATABASE")
navarre <- new_rtoi("Navarre", roi, rtp, dbp)
sat_search(region = navarre, product = "mcd43a4", dates = toi)

but trying whatever landsat or sentinel data search, for exemple:
sat_search(region = navarre, product = "ls7", dates = toi)
I got this message:
Warning message:
In .local(region, product, ...) :
  Satellite not supported, only modis, landsat and sentinel related products.
Any idea to solve this issue?
All the best,
Fred

**Comment by unai-perez** [comment]
Hi Fred,
The package uses the following product names.
-   for the Landsat program:
    -   Landsat 4-5 mission: "LANDSAT_TM_C1"
    -   Landsat-7 mission: "LANDSAT_ETM_C1"
    -   Landsat-8 mission: "LANDSAT_8_C1"

-   for the MODIS program:
    -   Terra satellite: "mod09ga"
    -   Aqua satellite: "myd09ga"

-   for the Sentinel program:
    -   Sentinel-2 mission: "S2MSI2A"
    -   Sentinel-3 mission: "SY_2_SYN___"

You can check the search vignette to see how it works "sat_search" function.
Cheers,
Unai

**Comment by Fredtouz** [comment]
Hi Unai,
thanks for your quick and clear answer! I used the function "show_variables()" to see how product can be called that's why I used "ls7" in the "sat_search" function, why may be confusing.

However, I still got a warning message but maybe not due to rsat package, while MODIS data are always available, for other data set I get this warning:

> sat_search(region = sgm, product = "LANDSAT_ETM_C1", dates = seq(as.Date("2010-07-01"),as.Date("2010-07-31"),1))
Searching scenes in the LANDSAT_ETM_C1 product...
Warning messages:
1: In .local(region, product, ...) :
  Error in Earth Explorer api connection. HTTP 404.
2: In .local(region, product, ...) :
  Error in Earth Explorer api connection. HTTP 404.
3: In .local(region, product, ...) :
  Error in Earth Explorer api connection. HTTP 404.
4: In .local(region, product, ...) :
  Error in Earth Explorer api connection. HTTP 404.
5: In .local(region, product, ...) :
  Error in Earth Explorer api connection. HTTP 404.
6: In .local(region, product, ...) :
  Error in Earth Explorer api connection. HTTP 404.
7: In .local(region, product, ...) :
  Cannot perform Landsat search, check your credentials and/or the api status: https://m2m.cr.usgs.gov/api/docs/json/

I checked my credantials and use the api without issue, It may just be a temporary Earth Explorer api connection issue.

Cheers,
Fred

**Comment by mthompsonecologic** [comment]
I realize this is a closed thread, but I'm getting the same error. Was the HTTP 404 resolved? I researched on the link provided (https://m2m.cr.usgs.gov/api/docs/json/) and it states:

"To check for a server error, inspect the HTTP response code; anything greater than 400 represents a server error. When these errors occur we encourage you to stop future script execution or introduce a larger delay between requests as these situations are typically not short outages or they identify potential fatal scripting errors."

Thank you,

Mark

**Comment by unai-perez** [comment]
Hi Mark,
I check the API and it works for me. Can you send me the example that doesn't work for you?
Cheers
Unai

**Comment by mthompsonecologic** [comment]
Thanks unai-perez...this is my code - I used my own data and the vignette:

```
## Vignette bounding box
ip <- st_sf(st_as_sfc(st_bbox(c(
  xmin = -9.755859,
  xmax =  4.746094,
  ymin = 35.91557,
  ymax = 44.02201 
), crs = 4326)))
toi <- seq(as.Date("2021-01-10"),as.Date("2021-01-15"),1)


## Chidliak bounding box
ch <- st_sf(st_as_sfc(st_bbox(c(
  xmin = -7245730,
  xmax = -7737919,
  ymin = 9190481,
  ymax = 9608584 
), crs = 3857)))

db.path <- "D:/EcoLogic 2021/Chidliak/Landsat/database"
ds.path <- "D:/EcoLogic 2021/Chidliak/Landsat/datasets"
dir.create(db.path)
dir.create(ds.path)

chidliak <- new_rtoi(name = "chidliak",
                     region = ch,
                     db_path = db.path,
                     rtoi_path = ds.path)

filomena <- new_rtoi(name = "filomena",
                     region = ip,
                     db_path = db.path,
                     rtoi_path = ds.path)

rtoi.files <- list.files(file.path(ds.path, "chidliak"), full.name = TRUE)
rtoi.files

rtoi.files <- list.files(file.path(ds.path, "filomena"), full.name = TRUE)
rtoi.files

chidliak <- read_rtoi(file.path(ds.path, "chidliak"))

filomena <- read_rtoi(file.path(ds.path, "filomena"))


print(chidliak)
print(filomena)

##Time of interest options
#toi <- seq(as.Date("1995-07-15"),as.Date("1995-09-15"),1)
#toi <- as.Date("2021-01-10") + 0:5

sat_search(region = chidliak,
           product = "LANDSAT_TM_C1",
           dates = seq(as.Date("1995-07-15"),as.Date("1995-09-15"),1)
           )

sat_search(region = filomena,
           product = "LANDSAT_TM_C1",
           dates = seq(as.Date("1995-07-15"),as.Date("1995-09-15"),1)
)
```

**Comment by unai-perez** [comment]
Hi Mark:
I test your code with the last version of the packages and some little changes and works, here you have the code:
## Vignette bounding box
ip <- st_sf(st_as_sfc(st_bbox(c(
  xmin = -9.755859,
  xmax =  4.746094,
  ymin = 35.91557,
  ymax = 44.02201 
), crs = 4326)))
toi <- seq(as.Date("2021-01-10"),as.Date("2021-01-15"),1)


## Chidliak bounding box
ch <- st_sf(st_as_sfc(st_bbox(c(
  xmin = -7245730,
  xmax = -7737919,
  ymin = 9190481,
  ymax = 9608584 
), crs = 3857)))
ch<-st_transform(ch,crs=st_crs(ip))

db.path <- "E:/EcoLogic 2021/Chidliak/Landsat/database"
ds.path <- "E:/EcoLogic 2021/Chidliak/Landsat/datasets"
dir.create(db.path,recursive =T)
dir.create(ds.path,recursive =T)

chidliak <- new_rtoi(name = "chidliak",
                     region = ch,
                     db_path = db.path,
                     rtoi_path = ds.path)

rtoi.files <- list.files(file.path(ds.path, "chidliak"), full.name = TRUE)
rtoi.files


chidliak <- read_rtoi(file.path(ds.path, "chidliak"))


print(chidliak)

##Time of interest options
#toi <- seq(as.Date("1995-07-15"),as.Date("1995-09-15"),1)
#toi <- as.Date("2021-01-10") + 0:5
set_credentials("username", "password") #put you passwords

rsat_search(region = chidliak,
           product = "LANDSAT_TM_C1",
           dates = seq(as.Date("1995-07-15"),as.Date("1995-09-15"),1)
)
rsat_preview(chidliak)
