### ISSUE TITLE
Package Removed from CRAN

### ISSUE THREAD

**Issue by thechibo** [ropensci/rsat#8]
Hello,

The package worked just fine on Friday. Today the `rsat_download()` function returns the following error.

`Downloading MOD09GA.A2002115.h11v04.006.2015147142413 image.
Error in curl_download(url, destfile = f, handle = c.handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) - The received certificate has expired.`

I tried to check the package vignette again to run some examples and found out the package has been archived on CRAN. Is this related to the error? Should I download the github version of the package?

Thank you in advance!
John

**Comment by ugaitz** [comment]
Hi,

It seems that the SSL certificate used by USGS has expired.
![Screenshot from 2022-07-18 10-51-03](https://user-images.githubusercontent.com/818873/179503291-c3bbbbe4-f1ee-426f-84f7-76ec8fc61ec0.png)
Without a valid certificate `rsat` cannot download any file from that service. The only option for now is to wait for USGS to update their certificate.
Looking in the LP DAAC website a post mentions that they are updating equipment and the service will not work until 10 a.m. CT on Tuesday, July 19, 2022.
[https://lpdaac.usgs.gov/news/extended-lp-daac-downtime-july-2022/](https://lpdaac.usgs.gov/news/extended-lp-daac-downtime-july-2022/)


Cheers,
Ugaitz

**Comment by thechibo** [comment]
Dear Ugaitz,

Thank you very much for the immediate reply!

Best Regards,
John
